twig:
    default_path: '%kernel.project_dir%/templates'
    # Nous indiquons que tous nos formulaire utiliseront les classes de BOOTSTRAP 5
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
